# Generated by Django 3.2.5 on 2021-12-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userToken', '0003_alter_usertoken_endtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orderNo', models.CharField(blank=True, max_length=100, null=True)),
                ('money', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.PositiveIntegerField()),
                ('create_time', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_Order',
            },
        ),
    ]
