# Generated by Django 3.2.5 on 2021-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userToken', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
