# Generated by Django 3.2.9 on 2022-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userToken', '0007_auto_20220101_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
