# Generated by Django 3.2.9 on 2022-01-02 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userToken', '0008_alter_products_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间'),
        ),
    ]
