# Generated by Django 3.2.5 on 2022-01-04 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userToken', '0009_auto_20220102_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='machineCode1',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='machineCode2',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='machineCode3',
        ),
        migrations.AlterModelTable(
            name='order',
            table='pay_Order',
        ),
        migrations.AlterModelTable(
            name='products',
            table='pay_products',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='pay_Token',
        ),
        migrations.CreateModel(
            name='machineCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machineCode', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_machineCodes',
            },
        ),
    ]
