# Generated by Django 3.2.5 on 2022-01-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_id', models.IntegerField(blank=True, max_length=20, null=True)),
                ('tage_type', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'study_tags',
            },
        ),
    ]
