# Generated by Django 3.2.5 on 2022-01-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
