# Generated by Django 3.2.5 on 2022-01-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_alter_tags_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField()),
                ('images', models.CharField(blank=True, default='images/python-default.png', max_length=100, null=True)),
                ('filePath', models.CharField(blank=True, default='images/python-default.png', max_length=100, null=True)),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.tags')),
            ],
            options={
                'db_table': 'study_articleContent',
            },
        ),
    ]
