# Generated by Django 3.2.5 on 2022-01-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_articlecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='filePath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
