# Generated by Django 3.2.5 on 2022-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=models.TextField(blank=True, default='请在此输入内容，支持markdown语法', null=True),
        ),
    ]
