# Generated by Django 3.2.5 on 2022-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_alter_notebook_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='clicks',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
