# Generated by Django 3.2.5 on 2022-04-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_articlecontent_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
