# Generated by Django 3.2.5 on 2022-05-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0012_collection_rate_skill'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collection',
            table='study_skill_collection',
        ),
        migrations.AlterModelTable(
            name='rate',
            table='study_skill_rate',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='study_skill',
        ),
    ]
