# Generated by Django 3.2.5 on 2022-05-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0013_auto_20220524_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=2),
        ),
    ]
