# Generated by Django 3.2.9 on 2022-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.TextField(default={})),
            ],
            options={
                'db_table': 'study_webConfig',
            },
        ),
    ]
