# Generated by Django 3.2.5 on 2022-01-14 04:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coins', models.IntegerField(blank=True, default=0, null=True)),
                ('exp', models.IntegerField(blank=True, default=0, null=True)),
                ('lv', models.IntegerField(blank=True, default=0, null=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 1, 14, 12, 59, 11, 437060))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pay_config',
            },
        ),
    ]
