# Generated by Django 3.2.5 on 2022-01-14 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payconfig',
            name='qd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payconfig',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 16, 39, 23, 929450)),
        ),
    ]
