# Generated by Django 3.2.9 on 2022-01-15 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0002_auto_20220114_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payconfig',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
