# Generated by Django 3.2.9 on 2022-01-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0003_alter_payconfig_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payconfig',
            name='userServerConfig',
            field=models.TextField(default='{}'),
        ),
    ]
