# Generated by Django 3.2.9 on 2022-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0005_alter_payconfig_userserverconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payconfig',
            name='userServerConfig',
            field=models.TextField(default={}),
        ),
    ]
