# Generated by Django 3.2.9 on 2022-01-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0007_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '已关闭'), (2, '已退款')]),
        ),
    ]
