# Generated by Django 3.2.9 on 2022-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0008_auto_20220124_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未付款'), (1, '已付款'), (2, '已关闭'), (3, '已退款')]),
        ),
    ]
