# Generated by Django 3.2.5 on 2022-04-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pay', '0010_payconfig_web_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDK',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdk', models.CharField(blank=True, max_length=26, null=True)),
                ('endTime', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('num', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('tmp1', models.CharField(blank=True, max_length=100, null=True)),
                ('tmp2', models.CharField(blank=True, max_length=100, null=True)),
                ('tmp3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pay_cdk',
            },
        ),
        migrations.CreateModel(
            name='cdkUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('coin', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('tmp1', models.CharField(blank=True, max_length=100, null=True)),
                ('tmp2', models.CharField(blank=True, max_length=100, null=True)),
                ('tmp3', models.CharField(blank=True, max_length=100, null=True)),
                ('cdk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pay.cdk')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cdk_user',
            },
        ),
    ]
