# Generated by Django 3.2.9 on 2021-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_newsimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cms_news_types',
            },
        ),
        migrations.AlterModelTable(
            name='newsimg',
            table='cms_news_img',
        ),
    ]
