# Generated by Django 3.2.5 on 2021-12-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_news_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimg',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notice.news'),
        ),
    ]
