# Generated by Django 3.2.5 on 2022-01-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebrityQuotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'study_cq',
            },
        ),
    ]
