# Generated by Django 3.2.9 on 2022-01-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_celebrityquotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='123456', max_length=100, null=True)),
                ('status', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'study_phone',
            },
        ),
    ]
