# Generated by Django 3.2.9 on 2022-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0006_auto_20220115_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='webConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('config', models.TextField(default={})),
            ],
        ),
    ]
