# Generated by Django 3.2.9 on 2022-01-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0007_webconfig'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webconfig',
            table='study_webConfig',
        ),
    ]
