# Generated by Django 3.2.5 on 2022-03-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0009_delete_webconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('group_type', models.PositiveIntegerField()),
                ('message_type', models.PositiveIntegerField()),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('creat_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_message',
            },
        ),
        migrations.CreateModel(
            name='MessageNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creat_time', models.DateTimeField(auto_now=True)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.message')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'study_message_new',
            },
        ),
    ]
